package com.example.cmps359_logger_final_project
// Nicholas Bourgeois, Jordan Williams
// C00222259, C00082940
// CMPS 359 - Android Programming
// Final Programming Project - A Speedrunning App, Loggers
// Certification of Authenticity:
// I certify that the code in this project are entirely of my own work
// the work of the members of my team or were caused to be generated by me or us
import androidx.annotation.NonNull
import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity (tableName = "times")
data class Times(@PrimaryKey(autoGenerate = true) @NonNull @ColumnInfo(name = "timeId")
var timeId: Int = 0,
    @ColumnInfo(name = "gameId") var gameId: Int,
    @ColumnInfo(name = "username") var username: String,
    @ColumnInfo(name = "totalTime") var totalTime: Long)