package com.example.cmps359_logger_final_project
// Nicholas Bourgeois, Jordan Williams
// C00222259, C00082940
// CMPS 359 - Android Programming
// Final Programming Project - A Speedrunning App, Loggers
// Certification of Authenticity:
// I certify that the code in this project are entirely of my own work
// the work of the members of my team or were caused to be generated by me or us

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
@Database(entities = [(Times::class)], version = 1)
abstract class TimesRoomDatabase: RoomDatabase() {
    abstract fun timesDao(): TimesDao
    companion object {
        private var INSTANCE: TimesRoomDatabase? = null
        internal fun getDatabase(context: Context): TimesRoomDatabase? {
            if (INSTANCE == null) {
                synchronized(TimesRoomDatabase::class.java) {
                    if (INSTANCE == null) {
                        INSTANCE =
                            Room.databaseBuilder<TimesRoomDatabase>(
                                context.applicationContext,
                                TimesRoomDatabase::class.java,
                                "times_database"
                            ).build()
                    }
                }
            }
            return INSTANCE
        }
    }
}